Feature/#63 atualizações de interface e funcionalidades de pagamento
desenvolvendo-me/startup-mission-base-rails pull request #65
Opened 2024-05-09 20:26 UTC by Pjmaciel

- [x] close #63 

Testes realizados:
![Mensal](https://github.com/desenvolvendo-me/startup-mission-base-rails/assets/134240484/911b901f-c19d-4351-8fd1-aaf5644232ab)
- [X] Teste de visualização alteraçao de pagamento mensal.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
![Anual](https://github.com/desenvolvendo-me/startup-mission-base-rails/assets/134240484/92a55a1c-a168-4a9e-87f7-88574a6b7448)
- [X] Teste de visualização alteraçao de pagamento anual.

2024-05-09 20:54 UTC, marcodotcastro commented on app/models/client.rb
> +#  user_id              :bigint
Os atribuções de gateway dever ser identificados para não gerar problema. Ou criar uma entidade para o gateway

2024-05-09 20:55 UTC, marcodotcastro commented on app/controllers/checkout_controller.rb
> +      cancel_url: checkout_cancel_url,
Migrar todo o código que não deveria estar no controller para camada de business.

2024-05-09 20:55 UTC, marcodotcastro commented on app/controllers/checkout_controller.rb
> +      'price_1PCXVjRpXIS2OKDBRNodCpRx'
Migrar todo o código que não deveria estar no controller para camada de business.

2024-05-09 20:59 UTC, marcodotcastro commented on app/controllers/page_controller.rb
> +      else
Migrar todo o código que não deveria estar no controller para camada de business.

2024-05-09 21:05 UTC, marcodotcastro requested changes
Favor refatorar os códigos e criar os testes

2024-05-16 21:57 UTC, Pjmaciel commented on app/controllers/checkout_controller.rb
> +      cancel_url: checkout_cancel_url,
Migração Realizada.

2024-05-16 21:57 UTC, Pjmaciel commented on app/controllers/checkout_controller.rb
> +      'price_1PCXVjRpXIS2OKDBRNodCpRx'
Migração feita.

2024-05-16 21:57 UTC, Pjmaciel commented on app/controllers/page_controller.rb
> +      else
Migraçao feita.

2024-05-16 22:08 UTC, Pjmaciel commented on app/models/client.rb
> +#  user_id              :bigint
Foi crada a entidade para o Gateway

2024-05-18 12:36 UTC, marcodotcastro approved these changes

2024-05-18 12:36 UTC, merged